### PR TITLE
Card/magnitudeofurbancampsites

### LINKED ISSUE #85: Magnitude of Urban Campsite Sweeps in Portland
# Story Card Request

**Project: Neighborhoods**
**Card Title: Campsite Sweeps over Time**

## Description / Wireframe

This card is a simple bar chart of campsite clean-ups over time, aggregated by week or by month. This card will be linked to a map representation of the point data over time as well and should be one summary in a more complete exploration of campsite sweeps from 10/2016-present (Issue #86 , Issue #87).

image

image

## Data Visualization / Design Concerns
At the moment, this card is relatively simple & it would be best bundled with other aggregations of the sweeps data, and/or closely linked to the interactive map of sweeps. 

## Context
This particular dataset has not been visualized or summarized by the city; currently a PDF report of clean-ups is posted online each week. The set of cards representing basic summaries of this dataset will be the first time anyone looks at this dataset as a whole. At the moment, representations are simple bar charts linked to an interactive map of point data over time, but suggestions for the overall structure of this set of cards would be welcome.

## Data Details (APIs)

Here is a link to an R notebook that shows the params & aggregation: https://drive.google.com/drive/u/0/folders/1-GMj8RvYb3PONTIVspmc5BMGO-mbSyWV

datasets:
 - camp_cleanups
 - neighborhoods

spatial join on:
- neighborhoods.geom
- camp_cleanups.geom

variables: 
- reportdate
- count of another column (e.g. lat or location) 

## About this data

Weekly reports of campsite sweeps are posted (PDF) to the Homelessness Toolkit (https://www.portlandoregon.gov/toolkit/69885), through One Point of Contact. The data reports which areas were cleaned up in any given week from October 2016-present, and reports plans for future sweeps in the upcoming week. A time-aware map of campsite reports is also available, and this dataset is also available to Hack OR (in progress; not coded for lat-long at this time): http://pdx.maps.arcgis.com/apps/TimeAware/index.html?appid=ac6a6abf1092482190984a5df9dfacb0

The text was extracted from these PDFs and geocoded (first pass through Google Maps API, second pass by hand). Ask Katy for a methods report (in progress).

### How did we calculate this
Methods report for dataset in progress; aggregation was calculated in R (see .Rmd file to reproduce).

### See the source
https://www.portlandoregon.gov/toolkit/71771

### PR DESCRIPTION
**Pull request by jaronheard**
This closes #85 and extends from the work done for #316.

image

It uses d3-time-format to add a date formatter to the formatters in the component library.

### CODE REVIEW

File: packages/2018-neighborhood-development/src/components/App/index.js [hunk 1]
```diff
@@ -21,7 +21,7 @@ const App = () => (
     heroTitle="Examining Local Patterns, Movement, and Our Sense of Place"
   >
     {/* <TheShapeOfANeighborhood /> */}
-    {/* <MagnitudeOfUrbanCampsiteSweeps /> */}
+    <MagnitudeOfUrbanCampsiteSweeps />
```
Comment (DingoEatingFuzz) [inline packages/2018-neighborhood-development/src/components/App/index.js]: What a satisfying diff.

File: packages/2018-neighborhood-development/src/components/MagnitudeOfUrbanCampsiteSweeps/index.js [hunk 2]
```diff
@@ -1,25 +1,108 @@
...
+      error,
+      magnitudeOfUrbanCampsiteSweeps,
+      // formattedDateData,
+    } = this.props;
+
+    if (isLoading) {
+      return <div className={cardLoading}>Loading...</div>;
+    } else if (!magnitudeOfUrbanCampsiteSweeps) {
+      return <div className={cardError}>{error ? `API ${error}` : 'Could not render Magnitude of Urban Campsite Sweeps.'}</div>;
+    }
```
Comment (DingoEatingFuzz) [inline packages/2018-neighborhood-development/src/components/MagnitudeOfUrbanCampsiteSweeps/index.js]: Does it make sense to use the `error` and `loading` states of CivicStoryCard here?

File: packages/2018-neighborhood-development/src/components/MagnitudeOfUrbanCampsiteSweeps/index.js [hunk 3]
```diff
@@ -1,25 +1,108 @@
...
+};
 
-// Connect this to the redux store when necessary
-export default MagnitudeOfUrbanCampsiteSweeps;
+export default connect(
+  state => ({
+    isLoading: isMagnitudeOfUrbanCampsiteSweepsPending(state),
+    error: catchMagnitudeOfUrbanCampsiteSweepsErrors(state),
+    magnitudeOfUrbanCampsiteSweeps: getMagnitudeOfUrbanCampsiteSweepsData(state),
+    // formattedDateData: formatDateData(state),
```
Comment (DingoEatingFuzz) [inline packages/2018-neighborhood-development/src/components/MagnitudeOfUrbanCampsiteSweeps/index.js]: If this isn't being used, it can be deleted.

**Comment by DingoEatingFuzz** [comment]
🚀
